name: market_place
description: jp&co and  digishare application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  http: ^0.12.2


  # google sign in

  odoo_api: ^1.0.4
  firebase_auth: ^0.18.3
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  carousel_slider: 2.3.1
  cached_network_image: 2.3.3
  flutter_svg: 0.18.1
  tab_indicator_styler: ^1.0.0
  flutter_sticky_header: ^0.5.0
  sliver_tools: ^0.1.10+1
  flutter_launcher_icons: ^0.8.0
  intl: ^0.16.0
  smooth_star_rating: ^1.1.1
  rounded_loading_button: ^1.0.14
  flutter_icons: ^1.1.0
  scoped_model: ^1.0.1
  curved_navigation_bar: ^0.3.7
  url_launcher: ^4.2.0+3
  # state management
  provider: ^4.3.2+2
  google_fonts: ^1.1.0
  # icon of google
  font_awesome_flutter: ^8.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/logos/facebook.jpg
    - assets/logos/google.jpg
    - assets/img/
    - assets/hotel/


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Langer
      fonts:
        - asset: assets/fonts/Langar-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

